### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by meimosor** [shensven/Crazy-Thursday#43]
debug模式可以跑起来。执行gradle打包时报错，信息如下：
![image](https://user-images.githubusercontent.com/31975932/185004035-6eddbdd3-fe38-4682-8bd4-936556be661e.png)

环境：win10/jdk11/gradle7.3.3

**Comment by shensven** [comment]
上游框架的问题 https://github.com/facebook/react-native/issues/34116

**Comment by meimosor** [comment]
大佬，还有个问题请教下，微信的那个MMTV库一直下载不下来？有什么解决办法吗？
![image](https://user-images.githubusercontent.com/31975932/185112179-dad4fa3f-b5f0-4e49-837c-b42c1507482c.png)

**Comment by meimosor** [comment]
> 大佬，还有个问题请教下，微信的那个MMTV库一直下载不下来？有什么解决办法吗？ ![image](https://user-images.githubusercontent.com/31975932/185112179-dad4fa3f-b5f0-4e49-837c-b42c1507482c.png)

镜像配置解决了
