### ISSUE TITLE
Android包名错误

### ISSUE THREAD

**Issue by meimosor** [shensven/Crazy-Thursday#81]
我在检查目录时发现Android包名和目录不一致，但是不清楚这样会导致什么错误。这个是写错了吗？
![image](https://user-images.githubusercontent.com/31975932/188097581-7d177a91-eb69-492a-96ee-3b56c9fdeaa5.png)

**Comment by shensven** [comment]
在这两个提交中更改过包名 https://github.com/shensven/Crazy-Thursday/commit/5a2769bf1a911f4bc7626bfa96352b22cd74ad8a https://github.com/shensven/Crazy-Thursday/commit/cee30174a4e67a48229f18a0c985a0afddab1821

**Comment by meimosor** [comment]
> 在这两个提交中更改过包名 [5a2769b](https://github.com/shensven/Crazy-Thursday/commit/5a2769bf1a911f4bc7626bfa96352b22cd74ad8a) [cee3017](https://github.com/shensven/Crazy-Thursday/commit/cee30174a4e67a48229f18a0c985a0afddab1821)

收到，谢谢！

**Comment by shensven** [comment]
不确定有没有加上，当时手动改的，没有使用 IDE，确实粗糙

**Comment by shensven** [comment]
感谢指出问题 @meimosor
